
package com.jm.cms.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Country", targetNamespace = "http://webservices.cms.jm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Country {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountries", targetNamespace = "http://webservices.cms.jm.com/", className = "com.jm.cms.webservices.GetCountries")
    @ResponseWrapper(localName = "getCountriesResponse", targetNamespace = "http://webservices.cms.jm.com/", className = "com.jm.cms.webservices.GetCountriesResponse")
    public List<String> getCountries();

}
