
package com.jm.cms.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Product", targetNamespace = "http://webservices.cms.jm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Product {


    /**
     * 
     * @return
     *     returns java.util.List<com.jm.cms.webservices.Product_Type>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://webservices.cms.jm.com/", className = "com.jm.cms.webservices.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://webservices.cms.jm.com/", className = "com.jm.cms.webservices.GetProductsResponse")
    public List<Product_Type> getProducts();

}
