
package com.jm.utilityservices.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountryService", targetNamespace = "http://webservices.utilityservices.jm.com/", wsdlLocation = "http://localhost:7001/utilityservices/country?wsdl")
public class CountryService
    extends Service
{

    private final static URL COUNTRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYSERVICE_EXCEPTION;
    private final static QName COUNTRYSERVICE_QNAME = new QName("http://webservices.utilityservices.jm.com/", "CountryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/utilityservices/country?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYSERVICE_WSDL_LOCATION = url;
        COUNTRYSERVICE_EXCEPTION = e;
    }

    public CountryService() {
        super(__getWsdlLocation(), COUNTRYSERVICE_QNAME);
    }

    public CountryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYSERVICE_QNAME, features);
    }

    public CountryService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYSERVICE_QNAME);
    }

    public CountryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYSERVICE_QNAME, features);
    }

    public CountryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Country
     */
    @WebEndpoint(name = "CountryPort")
    public Country getCountryPort() {
        return super.getPort(new QName("http://webservices.utilityservices.jm.com/", "CountryPort"), Country.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Country
     */
    @WebEndpoint(name = "CountryPort")
    public Country getCountryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.utilityservices.jm.com/", "CountryPort"), Country.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYSERVICE_EXCEPTION!= null) {
            throw COUNTRYSERVICE_EXCEPTION;
        }
        return COUNTRYSERVICE_WSDL_LOCATION;
    }

}
