
package com.jm.utilityservices.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://webservices.utilityservices.jm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservices.utilityservices.jm.com/", className = "com.jm.utilityservices.webservices.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservices.utilityservices.jm.com/", className = "com.jm.utilityservices.webservices.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod(operationName = "Hello")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://webservices.utilityservices.jm.com/", className = "com.jm.utilityservices.webservices.Hello_Type")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://webservices.utilityservices.jm.com/", className = "com.jm.utilityservices.webservices.HelloResponse")
    public void hello();

}
